Update Jenkinsfile

diff --git a/python-jenkins-argocd-k8s/Jenkinsfile b/python-jenkins-argocd-k8s/Jenkinsfile
--- a/python-jenkins-argocd-k8s/Jenkinsfile
+++ b/python-jenkins-argocd-k8s/Jenkinsfile
@@ -51,13 +51,22 @@ pipeline {
                 script {
                     withCredentials([usernamePassword(credentialsId: '1beef06e-952e-4633-a1a7-a641483784ac', passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) {
                         sh '''
-                        cat deploy.yaml
-                        sed -i '' "s/32/${BUILD_NUMBER}/g" deploy.yaml
-                        cat deploy.yaml
-                        git add deploy.yaml
-                        git commit -m 'Updated the deploy yaml | Jenkins Pipeline'
-                        git remote -v
-                        git push https://github.com/madhanshiva/cicd-demo-manifests-repo.git HEAD:main
+                        # List files for debugging
+                        ls -al
+                        
+                        # Check if deploy.yaml exists
+                        if [ -f deploy.yaml ]; then
+                            cat deploy.yaml
+                            sed -i "s/32/${BUILD_NUMBER}/g" deploy.yaml
+                            cat deploy.yaml
+                            git add deploy.yaml
+                            git commit -m 'Updated the deploy yaml | Jenkins Pipeline'
+                            git remote -v
+                            git push https://github.com/madhanshiva/cicd-end-to-end.git HEAD:main
+                        else
+                            echo "deploy.yaml not found"
+                            exit 1
+                        fi
                         '''
                     }
                 }
